const Helmets = [
  {
    id: 1,
    name: "ASHI High Class Performance Titanium",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet1.1.jpg",
      "./images/product/helmet1.2.jpg",
      "./images/product/helmet1.3.jpg",
      "./images/product/helmet1.4.jpg",
    ],
    price: 12999,
  },
  {
    id: 2,
    name: "ASHI High Class Guard Titanium",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet2.1.jpg",
      "./images/product/helmet2.2.jpg",
      "./images/product/helmet2.3.jpg",
      "./images/product/helmet2.4.jpg",
    ],
    price: 8999,
  },
  {
    id: 3,
    name: "ASHI High Class Performance Stainless Steel",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet3.1.jpg",
      "./images/product/helmet3.2.jpg",
      "./images/product/helmet3.3.jpg",
      "./images/product/helmet3.4.jpg",
    ],
    price: 8499,
  },
  {
    id: 4,
    name: "ASHI High Class Guard Stainless Steel",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet4.1.jpg",
      "./images/product/helmet4.2.jpg",
      "./images/product/helmet4.3.jpg",
      "./images/product/helmet4.4.jpg",
    ],
    price: 5999,
  },
  {
    id: 5,
    name: "ASHI Classic Match Performance Titanium",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet5.1.jpg",
      "./images/product/helmet5.2.jpg",
      "./images/product/helmet5.3.jpg",
      "./images/product/helmet5.4.jpg",
    ],
    price: 4149,
  },
  {
    id: 6,
    name: "ASHI Match Classic Pro Titanium",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet6.1.jpg",
      "./images/product/helmet6.2.jpg",
      "./images/product/helmet6.3.jpg",
      "./images/product/helmet6.4.jpg",
    ],
    price: 3999,
  },
  {
    id: 7,
    name: "ASHI High Class Guard Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet7.1.jpg",
      "./images/product/helmet7.2.jpg",
      "./images/product/helmet7.3.jpg",
      "./images/product/helmet7.4.jpg",
    ],
    price: 3399,
  },
  {
    id: 8,
    name: "ASHI Classic Match Performance Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet8.1.jpg",
      "./images/product/helmet8.2.jpg",
      "./images/product/helmet8.3.jpg",
      "./images/product/helmet8.4.jpg",
    ],
    price: 2149,
  },
  {
    id: 9,
    name: "ASHI Match Classic Pro Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet9.1.jpg",
      "./images/product/helmet9.2.jpg",
      "./images/product/helmet9.3.jpg",
      "./images/product/helmet9.4.jpg",
    ],
    price: 1999,
  },
  {
    id: 10,
    name: "ASHI Match Classic Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet10.1.jpg",
      "./images/product/helmet10.2.jpg",
      "./images/product/helmet10.3.jpg",
      "./images/product/helmet10.4.jpg",
    ],
    price: 1849,
  },
  {
    id: 11,
    name: "ASHI Classic Match Performance Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet11.1.jpg",
      "./images/product/helmet11.2.jpg",
      "./images/product/helmet11.3.jpg",
      "./images/product/helmet11.4.jpg",
    ],
    price: 1799,
  },
  {
    id: 12,
    name: "ASHI Little Pro Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet12.1.jpg",
      "./images/product/helmet12.2.jpg",
      "./images/product/helmet12.3.jpg",
      "./images/product/helmet12.4.jpg",
    ],
    price: 1699,
  },
  {
    id: 13,
    name: "ASHI Match Classic Pro Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet13.1.jpg",
      "./images/product/helmet13.2.jpg",
      "./images/product/helmet13.3.jpg",
      "./images/product/helmet13.4.jpg",
    ],
    price: 1649,
  },
  {
    id: 14,
    name: "ASHI Match Classic Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet14.1.jpg",
      "./images/product/helmet14.2.jpg",
      "./images/product/helmet14.3.jpg",
      "./images/product/helmet14.4.jpg",
    ],
    price: 1499,
  },
  {
    id: 15,
    name: "ASHI Little Pro Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet15.1.jpg",
      "./images/product/helmet15.2.jpg",
      "./images/product/helmet15.3.jpg",
      "./images/product/helmet15.4.jpg",
    ],
    price: 1349,
  },
  {
    id: 16,
    name: "ASHI Little Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "./images/product/helmet16.1.jpg",
      "./images/product/helmet16.2.jpg",
      "./images/product/helmet16.3.jpg",
      "./images/product/helmet16.4.jpg",
    ],
    price: 1049,
  },
];

const Acc = [
  {
    id: 1,
    name: "Neck-Guard High Class",
    size: ["S", "M", "L"],
    colors: ["Black", "Grey"],
    image: ["./images/product/acc1.1.jpg", "./images/product/acc1.2.jpg"],
    price: 999,
  },
  {
    id: 2,
    name: "Neck-Guard",
    size: ["S", "M", "L"],
    colors: ["Black"],
    image: ["./images/product/acc2.1.jpg", "./images/product/acc2.2.jpg"],
    price: 499,
  },
  {
    id: 3,
    name: "Chin Guard with Towel",
    size: ["One Size"],
    colors: ["Black"],
    image: ["./images/product/acc3.1.jpg", "./images/product/acc3.2.jpg"],
    price: 149,
  },
  {
    id: 4,
    name: "High Class Performance Ear Guard Set",
    size: ["One Size"],
    colors: ["Black"],
    image: ["./images/product/acc4.1.jpg", "./images/product/acc4.2.jpg"],
    price: 149,
  },
  {
    id: 5,
    name: "Sweatband",
    size: ["6MM", "8MM", "10MM", "12MM"],
    colors: ["Gold", "Grey"],
    image: ["./images/product/acc5.1.jpg", "./images/product/acc5.1.jpg"],
    price: 99,
  },
  {
    id: 6,
    name: "Inner Cushions",
    size: ["One Size"],
    colors: ["Silver"],
    image: ["./images/product/acc6.1.jpg", "./images/product/acc6.2.jpg"],
    price: 99,
  },
  {
    id: 7,
    name: "Rear Cushion Pad",
    size: ["8MM", "10MM"],
    colors: ["Black"],
    image: ["./images/product/acc7.1.jpg", "./images/product/acc7.2.jpg"],
    price: 99,
  },
  {
    id: 8,
    name: "Chin Guard without Towel",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["./images/product/acc8.1.jpg", "./images/product/acc8.1.jpg"],
    price: 69,
  },
  {
    id: 9,
    name: "High Class Ear Guard Set",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["./images/product/acc9.1.jpg", "./images/product/acc9.1.jpg"],
    price: 99,
  },
  {
    id: 10,
    name: "Rear Strap Pad Without Towel",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["./images/product/acc10.1.jpg", "./images/product/acc10.1.jpg"],
    price: 49,
  },
  {
    id: 11,
    name: "Nut Pack(4)",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["./images/product/acc11.1.jpg", "./images/product/acc11.1.jpg"],
    price: 65,
  },
];

export { Helmets, Acc };
