const Items = [
  {
    id: 1,
    name: "ASHI High Class Performance Titanium",
    size: ["S", "M", "L", "XL"],
    colors: [
      "navy",
      "green",
      "maroon",
      "black",
      "red",
      "skyblue",
      "gold",
      "blue",
    ],
    image: [
      "/images/product/helmet1.1.jpg",
      "/images/product/helmet1.2.jpg",
      "/images/product/helmet1.3.jpg",
      "/images/product/helmet1.4.jpg",
    ],
    desc: [
      "Weighs approximately 780gms",
      "High grade Xenoy composite shell.",
      "A+ American EPS liner for increased safety and shock absorption",
      "Top grade lightweight titanium with natural finish helps in better visibility and utmost strength",
      "Advanced air flow system",
      "Permanently attached ASHI embossed side plates",
      "Improved rear retention system with cushion pads for better ﬁt and comfort",
      "New improved ﬁxed grille with increased facial and side protection",
      "Removable and washable sweatband",
      "Extended at the back for increased safety",
    ],
    comp: [
      "Complimentary HIGH CLASS Neck Guard ",
      "SPARES",
      "Mesh bag, SWEATBAND, 2 Rear cushion pads, 2 Round inner cushions, 8 Round Velcro sets, CHIN GUARD",
    ],
    price: 12999,
  },
  {
    id: 2,
    name: "ASHI High Class Guard Titanium",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet2.1.jpg",
      "/images/product/helmet2.2.jpg",
      "/images/product/helmet2.3.jpg",
      "/images/product/helmet2.4.jpg",
    ],
    desc: [
      "Weighs approximately 790gms",
      "High grade ABS composite shell",
      "EPS liner for increased safety",
      "Advanced air flow system",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort",
      "Permanently attached ASHI embossed side plates.",
      "New improved ﬁxed grille with increased facial and side protection",
      "Removable and washable Sweatband.",
      "Extended at the back for increased safety",
    ],
    comp: [
      "Complimentary HIGH CLASS Neck Guard.",
      "SPARES",
      "Mesh bag, Sweatband, 2 Rear cushion pads, 2 Round inner cushions, 4 Round Velcro sets.",
    ],
    price: 8999,
  },
  {
    id: 3,
    name: "ASHI High Class Performance Stainless Steel",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet3.1.jpg",
      "/images/product/helmet3.2.jpg",
      "/images/product/helmet3.3.jpg",
      "/images/product/helmet3.4.jpg",
    ],
    desc: [
      "Weighs approximately 900gms",
      "High grade Xenoy composite shell",
      "A+ American EPS liner for increased safety and shock absorption",
      "Top grade stainless steel with natural finish helps in better visibility",
      "Advanced air flow system",
      "New permanently attached ASHI embossed side plates",
      "Improved rear retention system with cushion pads for better ﬁt and comfort.",
      "New improved ﬁxed grille with increased facial and side protection",
      "Removable and washable sweatband",
      "Extended at the back for increased safety",
      "Conforms to latest ICC/BS 2013 safety standards with both 4 3/4 and 5 1/2 OZ ball",
    ],
    comp: [
      "Complimentary HIGH CLASS Neck Guard ",
      "SPARES",
      "Mesh bag, SWEATBAND, 2 Rear cushion pads, 2 Round inner cushions, 8 Round Velcro sets, CHIN GUARD.",
    ],
    price: 8499,
  },
  {
    id: 4,
    name: "ASHI High Class Guard Stainless Steel",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet4.1.jpg",
      "/images/product/helmet4.2.jpg",
      "/images/product/helmet4.3.jpg",
      "/images/product/helmet4.4.jpg",
    ],
    desc: [
      "Weighs approximately 920gms",
      "High grade ABS composite shell",
      "EPS liner for increased safety",
      "Grade-2 stainless steel with natural finish helps in better visibility.",
      "Advanced air flow system",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort",
      "New improved ﬁxed grille with increased facial and side protection",
      "Removable and washable sweatband",
      "Extended at the back for increased safety",
    ],
    comp: [
      "Complimentary HIGH CLASS Neck Guard",
      "SPARES",
      "Mesh bag, Sweatband, 2 Rear cushion pads, 2 Round inner cushions, 4 Round Velcro sets.",
    ],
    price: 5999,
  },
  {
    id: 5,
    name: "ASHI Classic Match Performance Titanium",
    size: ["S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet5.1.jpg",
      "/images/product/helmet5.2.jpg",
      "/images/product/helmet5.3.jpg",
      "/images/product/helmet5.4.jpg",
    ],
    desc: [
      "Weighs approximately 780gms.",
      "Classic Match Performance is the most commonly used helmet in the game of cricket.",
      "High grade ABS composite shell.",
      "Removable and washable sweatband and inner cushions.",
      "Advanced air flow system.",
      "Traditional cut-shoulder visor designed for better movement.",
      "Visor can be adjusted as required. ",
      "We suggest to keep the minimum gap possible between the peak and the visor at all times so as to avoid penetration of the ball.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort. ",
      "Shock Resistant, Sweat Absorbent, Breathable U Foam lining to keep dry, clean and comfortable",
      "Moulded Eva foam padding for better protection and cushioning",
    ],
    comp: [
      "Complimentary Neck Guard ",
      "SPARES",
      "Mesh bag, SWEATBAND, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD.",
    ],
    price: 4149,
  },
  {
    id: 6,
    name: "ASHI Match Classic Pro Titanium",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet6.1.jpg",
      "/images/product/helmet6.2.jpg",
      "/images/product/helmet6.3.jpg",
      "/images/product/helmet6.4.jpg",
    ],
    desc: [
      "Weighs approximately 740gms.",
      "Match Classic PRO is the most commonly used helmet in the game of cricket.",
      "High grade ABS Black Carbon composite shell",
      "Removable and washable sweatband and inner cushions.",
      "Advanced air flow system.",
      "Traditional cut-shoulder visor designed for better movement.",
      "Visor can be adjusted as required. ",
      "We suggest to keep the minimum gap possible between the peak and the visor at all times so as to avoid penetration of the ball.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort. ",
      "Eva foam padding for better protection and cushioning",
    ],
    comp: [
      "Complimentary Neck Guard",
      "SPARES",
      "Mesh bag, SWEATBAND, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD",
    ],
    price: 3999,
  },
  {
    id: 7,
    name: "ASHI High Class Guard Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet7.1.jpg",
      "/images/product/helmet7.2.jpg",
      "/images/product/helmet7.3.jpg",
      "/images/product/helmet7.4.jpg",
    ],
    desc: [
      "Weighs approximately 950gms.",
      "High grade ABS composite shell.,",
      "EPS liner for increased safety.",
      "Top grade steel with dark grey powder coated finish helps in better visibility.",
      "New permanently attached ASHI embossed side plates.",
      "Improved rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort.",
      "New improved ﬁxed grille with increased facial and side protection.",
      "Removable and washable sweatband.",
      " Extended at the back for increased safety.",
    ],
    comp: [
      "Complimentary HIGH CLASS Neck Guard",
      "SPARES",
      "Mesh bag, 4 Round Velcro sets",
    ],
    price: 3399,
  },
  {
    id: 8,
    name: "ASHI Classic Match Performance Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet8.1.jpg",
      "/images/product/helmet8.2.jpg",
      "/images/product/helmet8.3.jpg",
      "/images/product/helmet8.4.jpg",
    ],
    desc: [
      "Weighs approximately 810gms.",
      "Classic Match Performance is the most commonly used helmet in the game of cricket.",
      "High grade ABS composite shell.",
      "Removable and washable sweatband and inner cushions.",
      "Advanced air flow system.",
      "Traditional cut-shoulder visor designed for better movement.",
      "Visor can be adjusted as required. ",
      "      We suggest to keep the minimum gap possible between the peak and the visor at all times so as to avoid penetration of the ball.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort. ",
      "Shock Resistant, Sweat Absorbent, Breathable U Foam lining to keep dry, clean and comfortable",
      "Moulded Eva foam padding for better protection and cushioning.",
    ],
    comp: [
      "Complimentary Neck Guard",
      "SPARES",
      "Mesh bag, SWEATBAND, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD.",
    ],
    price: 2149,
  },
  {
    id: 9,
    name: "ASHI Match Classic Pro Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet9.1.jpg",
      "/images/product/helmet9.2.jpg",
      "/images/product/helmet9.3.jpg",
      "/images/product/helmet9.4.jpg",
    ],
    desc: [
      "Weighs approximately 830gms.",
      "Match Classic PRO is the most commonly used helmet in the game of cricket.",
      "High grade ABS Black Carbon composite shell.",
      "Removable and washable sweatband and inner cushions.",
      "Advanced air flow system.",
      "Traditional cut-shoulder visor designed for better movement.",
      " Visor can be adjusted as required. ",
      "We suggest to keep the minimum gap possible between the peak and the visor at all times so as to avoid penetration of the ball.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort. ",
      "Eva foam padding for better protection and cushioning.",
    ],
    comp: [
      "Complimentary Neck Guard",
      "SPARES",
      "Mesh bag, SWEATBAND, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD.",
    ],
    price: 1999,
  },
  {
    id: 10,
    name: "ASHI Match Classic Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet10.1.jpg",
      "/images/product/helmet10.2.jpg",
      "/images/product/helmet10.3.jpg",
      "/images/product/helmet10.4.jpg",
    ],
    desc: [
      "Weighs approximately 780gms.",
      "Match Classic is the most commonly used helmet in the game of cricket.",
      "Superfine satin cloth covered ABS Black Carbon outer shell.",
      "Removable and washable sweatband.",
      "Air vent holes.",
      "Eva foam padding for better protection and cushioning.",
      "Quick release buckle and fastening strap for secure fit and increased safety.",
      "Adjustable Stainless steel visor for custom fit.",
      "Increased facial and side protection.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort",
    ],
    comp: [
      "Complimentary Neck Guard",
      "SPARES",
      "Mesh bag, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD",
    ],
    price: 1849,
  },
  {
    id: 11,
    name: "ASHI Classic Match Performance Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet11.1.jpg",
      "/images/product/helmet11.2.jpg",
      "/images/product/helmet11.3.jpg",
      "/images/product/helmet11.4.jpg",
    ],
    desc: [
      "Weighs approximately 860gms.",
      "Classic Match Performance is the most commonly used helmet in the game of cricket.",
      "High grade ABS composite shell.",
      "Removable and washable sweatband and inner cushions.",
      "Advanced air flow system.",
      "Traditional cut-shoulder visor designed for better movement.",
      "Visor can be adjusted as required.",
      "We suggest to keep the minimum gap possible between the peak and the visor at all times so as to avoid penetration of the ball.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort. ",
      "Shock Resistant, Sweat Absorbent, Breathable U Foam lining to keep dry.",
      "Moulded Eva foam padding for better protection and cushioning",
    ],

    comp: [
      "Complimentary Neck Guard ",
      "SPARES",
      "Mesh bag, SWEATBAND, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD.",
    ],
    price: 1799,
  },
  {
    id: 12,
    name: "ASHI Little Pro Stainless Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet12.1.jpg",
      "/images/product/helmet12.2.jpg",
      "/images/product/helmet12.3.jpg",
      "/images/product/helmet12.4.jpg",
    ],
    desc: [
      "Weighs approximately 750gms.",
      "Little PRO is the most commonly used helmet in the game of cricket.",
      "Superfine satin cloth covered ABS outer shell.",
      "Removable and washable sweatband.",
      "Air vent holes.",
      "Eva foam padding for better protection and cushioning.",
      "Quick release buckle and fastening strap for secure fit and increased safety.",
      "Adjustable Stainless steel visor for custom fit.",
      "Increased facial and side protection.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort.",
    ],
    comp: [
      "Complimentary Neck Guard ",
      "SPARES",
      "2 Nut Pack, 4 Round Velcro sets, CHIN GUARD",
    ],
    price: 1699,
  },
  {
    id: 13,
    name: "ASHI Match Classic Pro Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet13.1.jpg",
      "/images/product/helmet13.2.jpg",
      "/images/product/helmet13.3.jpg",
      "/images/product/helmet13.4.jpg",
    ],
    desc: [
      "Weighs approximately 860gms.",
      "Match Classic PRO is the most commonly used helmet in the game of cricket.",
      "High grade ABS Black Carbon composite shell.",
      "Removable and washable sweatband and inner cushions.",
      "Advanced air flow system.",
      "Traditional cut-shoulder visor designed for better movement.",
      "Visor can be adjusted as required. ",
      "We suggest to keep the minimum gap possible between the peak and the visor at all times so as to avoid penetration of the ball.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort. ",
      "Eva foam padding for better protection and cushioning.",
    ],
    comp: [
      "Complimentary Neck Guard ",
      " SPARES",
      "Mesh bag, SWEATBAND, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD.",
    ],
    price: 1649,
  },
  {
    id: 14,
    name: "ASHI Match Classic Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet14.1.jpg",
      "/images/product/helmet14.2.jpg",
      "/images/product/helmet14.3.jpg",
      "/images/product/helmet14.4.jpg",
    ],
    desc: [
      "Weighs approximately 830gms.",
      "Match Classic is the most commonly used helmet in the game of cricket.",
      "Superfine satin cloth covered ABS Black Carbon outer shell.",
      "Removable and washable sweat band.",
      "Air vent holes.",
      "Eva foam padding for better protection and cushioning.",
      "Quick release buckle and fastening strap for secure fit and increased safety.",
      "Adjustable Stainless steel visor for custom fit.",
      "Increased facial and side protection.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort",
    ],

    comp: [
      "Complimentary Neck Guard ",
      "SPARES",
      "Mesh bag, 2 Nut Pack, 4 Round Velcro sets, CHIN GUARD.",
    ],
    price: 1499,
  },
  {
    id: 15,
    name: "ASHI Little Pro Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet15.1.jpg",
      "/images/product/helmet15.2.jpg",
      "/images/product/helmet15.3.jpg",
      "/images/product/helmet15.4.jpg",
    ],
    desc: [
      "Weighs approximately 780gms.",
      "Little PRO is the most commonly used helmet in the game of cricket.",
      "Superfine satin cloth covered ABS outer shell.",
      "Removable and washable sweatband.",
      "Air vent holes.",
      " Eva foam padding for better protection and cushioning.",
      "Quick release buckle and fastening strap for secure fit and increased safety.",
      "Adjustable Stainless steel visor for custom fit.",
      "Increased facial and side protection.",
      "Rear retention system with Velcro straps and pads helps in getting the desired ﬁt and comfort.",
    ],
    comp: [
      "Complimentary Neck Guard",
      "SPARES",
      "2 Nut Pack, 4 Round Velcro sets, CHIN GUARD",
    ],
    price: 1349,
  },
  {
    id: 16,
    name: "ASHI Little Steel",
    size: ["JR", "S", "M", "L", "XL"],
    colors: [
      "Navy",
      "Green",
      "Maroon",
      "Black",
      "Red",
      "S.Blue",
      "Gold",
      "R.Blue",
    ],
    image: [
      "/images/product/helmet16.1.jpg",
      "/images/product/helmet16.2.jpg",
      "/images/product/helmet16.3.jpg",
      "/images/product/helmet16.4.jpg",
    ],
    desc: [
      "Weighs approximately 780gms.",
      "Little is the most commonly used helmet in the game of cricket.",
      "ABS outer shell.",
      "Traditional shoulder-cut design for better movement.",
      "Eva foam padding for better protection and cushioning.",
      "Removable and washable sweatband.",
      "Extended at the back for more safety.",
      "Adjustable steel visor for custom fit.",
      "Rear retention system with Velcro straps and pads helps get a desired fit and comfort.",
    ],
    comp: [
      "SPARES",
      "2 Nut Pack, 4 Round Velcro sets, Inner Cushions, CHIN GUARD",
    ],
    price: 1049,
  },
  {
    id: 17,
    name: "Neck-Guard High Class",
    size: ["S", "M", "L"],
    colors: ["Black", "Grey"],
    image: ["/images/product/acc1.1.jpg", "/images/product/acc1.2.jpg"],
    price: 999,
    desc: [
      "New developed helmet Arc-shaped neck-guard moulded with hard outer and semi-soft inner foams.",
      "Preferred choice of international cricketers. ",
      "Unique design reduces contact with vulnerable areas.",
      "High density closed cell outer foam.",
      "Velcro closure system for improved flexibility and protection.",
      "Special foams and moulding makes it a lightweight and very strong product.",
    ],
    comp: [""],
  },
  {
    id: 18,
    name: "Neck-Guard",
    size: ["S", "M", "L"],
    colors: ["Black"],
    image: ["/images/product/acc2.1.jpg", "/images/product/acc2.2.jpg"],
    price: 499,
    desc: [
      "Unique design reduces contact with vulnerable areas.",
      "High density closed cell foam.",
      "Velcro closure system for improved flexibility and protection.",
    ],
    comp: [],
  },
  {
    id: 19,
    name: "Chin Guard with Towel",
    size: ["One Size"],
    colors: ["Black"],
    image: ["/images/product/acc3.1.jpg", "/images/product/acc3.2.jpg"],
    price: 149,
    desc: [],
    comp: [],
  },
  {
    id: 20,
    name: "High Class Performance Ear Guard Set",
    size: ["One Size"],
    colors: ["Black"],
    image: ["/images/product/acc4.1.jpg", "/images/product/acc4.2.jpg"],
    price: 149,
    desc: [],
    comp: [],
  },
  {
    id: 21,
    name: "Sweatband",
    size: ["6MM", "8MM", "10MM", "12MM"],
    colors: ["Gold", "Grey"],
    image: ["/images/product/acc5.1.jpg", "/images/product/acc5.1.jpg"],
    price: 99,
    desc: [],
    comp: [],
  },
  {
    id: 22,
    name: "Inner Cushions",
    size: ["One Size"],
    colors: ["Silver"],
    image: ["/images/product/acc6.1.jpg", "/images/product/acc6.2.jpg"],
    price: 99,
    desc: [],
    comp: [],
  },
  {
    id: 23,
    name: "Rear Cushion Pad",
    size: ["8MM", "10MM"],
    colors: ["Black"],
    image: ["/images/product/acc7.1.jpg", "/images/product/acc7.2.jpg"],
    price: 99,
    desc: [],
    comp: [],
  },
  {
    id: 24,
    name: "Chin Guard without Towel",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["/images/product/acc8.1.jpg", "/images/product/acc8.1.jpg"],
    price: 69,
    desc: [],
    comp: [],
  },
  {
    id: 25,
    name: "High Class Ear Guard Set",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["/images/product/acc9.1.jpg", "/images/product/acc9.1.jpg"],
    price: 99,
    desc: [],
    comp: [],
  },
  {
    id: 26,
    name: "Rear Strap Pad Without Towel",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["/images/product/acc10.1.jpg", "/images/product/acc10.1.jpg"],
    price: 49,
    desc: [],
    comp: [],
  },
  {
    id: 27,
    name: "Nut Pack(4)",
    size: ["One Size"],
    colors: ["Grey"],
    image: ["/images/product/acc11.1.jpg", "/images/product/acc11.1.jpg"],
    price: 65,
    desc: [],
    comp: [],
  },
];

// const Acc = [
//   {
//     id: 1,
//     name: "Neck-Guard High Class",
//     size: ["S", "M", "L"],
//     colors: ["Black", "Grey"],
//     image: ["./images/product/acc1.1.jpg", "./images/product/acc1.2.jpg"],
//     price: 999,
//   },
//   {
//     id: 2,
//     name: "Neck-Guard",
//     size: ["S", "M", "L"],
//     colors: ["Black"],
//     image: ["./images/product/acc2.1.jpg", "./images/product/acc2.2.jpg"],
//     price: 499,
//   },
//   {
//     id: 3,
//     name: "Chin Guard with Towel",
//     size: ["One Size"],
//     colors: ["Black"],
//     image: ["./images/product/acc3.1.jpg", "./images/product/acc3.2.jpg"],
//     price: 149,
//   },
//   {
//     id: 4,
//     name: "High Class Performance Ear Guard Set",
//     size: ["One Size"],
//     colors: ["Black"],
//     image: ["./images/product/acc4.1.jpg", "./images/product/acc4.2.jpg"],
//     price: 149,
//   },
//   {
//     id: 5,
//     name: "Sweatband",
//     size: ["6MM", "8MM", "10MM", "12MM"],
//     colors: ["Gold", "Grey"],
//     image: ["./images/product/acc5.1.jpg", "./images/product/acc5.1.jpg"],
//     price: 99,
//   },
//   {
//     id: 6,
//     name: "Inner Cushions",
//     size: ["One Size"],
//     colors: ["Silver"],
//     image: ["./images/product/acc6.1.jpg", "./images/product/acc6.2.jpg"],
//     price: 99,
//   },
//   {
//     id: 7,
//     name: "Rear Cushion Pad",
//     size: ["8MM", "10MM"],
//     colors: ["Black"],
//     image: ["./images/product/acc7.1.jpg", "./images/product/acc7.2.jpg"],
//     price: 99,
//   },
//   {
//     id: 8,
//     name: "Chin Guard without Towel",
//     size: ["One Size"],
//     colors: ["Grey"],
//     image: ["./images/product/acc8.1.jpg", "./images/product/acc8.1.jpg"],
//     price: 69,
//   },
//   {
//     id: 9,
//     name: "High Class Ear Guard Set",
//     size: ["One Size"],
//     colors: ["Grey"],
//     image: ["./images/product/acc9.1.jpg", "./images/product/acc9.1.jpg"],
//     price: 99,
//   },
//   {
//     id: 10,
//     name: "Rear Strap Pad Without Towel",
//     size: ["One Size"],
//     colors: ["Grey"],
//     image: ["./images/product/acc10.1.jpg", "./images/product/acc10.1.jpg"],
//     price: 49,
//   },
//   {
//     id: 11,
//     name: "Nut Pack(4)",
//     size: ["One Size"],
//     colors: ["Grey"],
//     image: ["./images/product/acc11.1.jpg", "./images/product/acc11.1.jpg"],
//     price: 65,
//   },
// ];

export default Items;
